/*
SQL Server:
Retrieves details about foreign key relationships for a specific primary key,
including related tables and columns, using INFORMATION_SCHEMA views.
*/

SELECT
    TC.TABLE_SCHEMA, 'FOREIGN KEY' AS object_type,
    TC2.TABLE_NAME AS [object_name],
    NULL AS COLUMN_NAME,
    NULL AS ORDINAL_POSITION,
    NULL AS COLUMN_DEFAULT,
    NULL AS IS_NULLABLE,
    NULL AS DATA_TYPE,
    TC.CONSTRAINT_NAME AS PK_name,
    NULL AS PK_type,
    TC.TABLE_NAME AS PK_table_name,
    CONCAT('[', CCU1.COLUMN_NAME, ']') AS PK_column_name,
    RC.CONSTRAINT_NAME AS FK_name,
    CONCAT('[', CCU2.Column_Name, ']') AS FK_column_name,
    NULL AS view_definition
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU1 ON TC.TABLE_NAME = CCU1.TABLE_NAME AND TC.TABLE_SCHEMA = CCU1.TABLE_SCHEMA AND TC.CONSTRAINT_NAME = CCU1.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON TC.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME AND TC.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC2 ON TC2.CONSTRAINT_NAME = RC.CONSTRAINT_NAME AND TC.CONSTRAINT_SCHEMA = TC2.CONSTRAINT_SCHEMA
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU2 ON RC.CONSTRAINT_NAME = CCU2.CONSTRAINT_NAME AND RC.CONSTRAINT_SCHEMA = CCU2.CONSTRAINT_SCHEMA
WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
AND TC.TABLE_SCHEMA = 'table_schema'
AND TC.TABLE_NAME = 'table_name'